### ISSUE TITLE
nhentai not working 

### ISSUE THREAD

**Issue by luffyx10** [HDoujinDownloader/HDoujinDownloader#126]
nhentai by add and by clipmonitor isn't working

**Comment by HDoujinDownloader** [comment]
It's probably because they've enabled Cloudflare's anti-bot services again (see #117). It seems to come up every few days before disappearing again shortly thereafter.

In the meantime, if you use the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver), downloads should proceed as normal again.

**Comment by Gin-no-kami** [comment]
Is it possible to use the FlareSolverr plugin when running via wine? I am assuming not, since the plugin is 64bit while HDoujin is 32bit. I tried to get everything running in a 64bit wine prefix but I couldn't get it working.

**Comment by HDoujinDownloader** [comment]
@Gin-no-kami It runs as a separate process, so the architecture difference doesn't really matter. It acts as a proxy server that HDoujin Downloader routes its requests through.

The issue you're probably encountering is that the paths to the FlareSolverr executable are set for Windows, and I haven't tested them on other platforms. I need to do that so it can be started automatically.

In the meantime, you can go into the plugin folder and start FlareSolverr manually. Since it just acts as a proxy server, it doesn't matter who starts it, as long as it's running.
