### ISSUE TITLE
Manta.net has been updated

### ISSUE THREAD

**Issue by Fallen98** [HDoujinDownloader/HDoujinDownloader#166]
It seems like https://manta.net/ has been updated and now has an actual web version

Would it be possible to update the extension and for login support to be added?

**Comment by HDoujinDownloader** [comment]
I just updated the module for this site (4ed7f26), so it should be working again. 

However, I have yet to add login support (#192). It's kind of tricky since it uses a third-party login instead of offering its own accounts, but you might be able to get by by manually copying your session cookies into HDoujin Downloader after logging in.
