### ISSUE TITLE
bug for nhentai.net

### ISSUE THREAD

**Issue by MimoKar** [HDoujinDownloader/HDoujinDownloader#211]
Hello,

when I add multiple links from nhentai.net that some of the downloads are ending with error missing files. When I look to folder I see that there are downloaded files from previous location in list, f.e. for gallery https://nhentai.net/g/11 it contains files from gallery https://nhentai.net/g/10.
When I put this as simple gallery, then it is downloaded correctly.
Other sites are not affected.

**Comment by MimoKar** [comment]
After some observation, I think it has something with flare solver. This situation happens when flare solver is used for enqueue and at the same time for download. It seems that for download is used same URL as for queuing ... Similar behavior I see when multiple downloads are used.
When I leave the app to create queue from list, and then I start one download, then it is working fine.

**Comment by HDoujinDownloader** [comment]
Thanks a lot for the update; it's very possible that the issue is related to FlareSolverr. 

I tried doing what you described (starting a bunch of downloads and queuing some URLs at the same time), but I'm having trouble reproducing it with the [latest release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/v2023.5.6.0-rc.7). 

What versions of HDoujin Downloader/FlareSolverr are you experiencing this with? Try using the latest versions of both, and let me know what happens.

In the meantime, I'll keep investigating on my end and see if I can figure something out.

**Comment by MimoKar** [comment]
Here is a short log file from it. It happens on latest HD and flaresollver (3.2.0) too.
[1685878484.zip](https://github.com/HDoujinDownloader/HDoujinDownloader/files/11645628/1685878484.zip)

**Comment by MimoKar** [comment]
Hi,

seems that in rc9 it working fine, so for me, it is fixed.

**Comment by HDoujinDownloader** [comment]
Glad to hear it! I did update FlareSolverr for that release, so it might've been a bug with FlareSolverr after all.
