### ISSUE TITLE
Failed "Completed" download from nhentai.net

### ISSUE THREAD

**Issue by Macadudledooo** [HDoujinDownloader/HDoujinDownloader#235]
Status shows it has completed but it doesn't download anything.
Apparently I am forbidden of access?

![image](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/76395856/e7b36023-87c1-47b6-80a1-7f8c36faa6a7)
Debug Log: [1692022051-debug.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/12335886/1692022051-debug.log)

~might or might not be too lazy/shy to contact support directly~

**Comment by HDoujinDownloader** [comment]
Too shy, huh? Am I that intimidating?😢

I think you downloaded the executable-only version of HDoujin Downloader, which doesn't include the DLLs required to run the Lua modules. This is required for downloading from nhentai properly, which is why you're running into this issue.

Try downloading the latest pre-release of HDoujin Downloader from [here](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/download/v2023.6.26.0-rc.10/HDoujin.Downloader-2023.6.24.0-rc.10-win.zip), and then download the latest version of the FlareSolverr plugin by following the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver#updating-the-flaresolverr-plugin). The latter is required to bypass the Cloudflare check when accessing nhentai.

After that, it should work!

**Comment by Macadudledooo** [comment]
oh tyvm
