### ISSUE TITLE
Redirect changed manga URLs from Asura Scans

### ISSUE THREAD

**Issue by Zervox** [HDoujinDownloader/HDoujinDownloader#238]
Asurascans needs to have a setting for the site which allows a regex replace of

url = RegexReplace(url, '/[0-9]+-', '/'..settingsid..'-') before checking/connection
too many of the links does not allow non /number- id to be reached

alternatively to support other websites that does the same thing, allow to mass edit bookmark urls using regex

**Comment by HDoujinDownloader** [comment]
To make sure I understand correctly-- It seems AsuraScans changed the format of their URLs, and your bookmarks are no longer pointing to the right place anymore?

Could you send me some example URLs to look at (e.g. before and after fixing the URL)?

**Comment by HDoujinDownloader** [comment]
All right, I updated the module to get the current numeric prefix and automatically apply it to URLs before attempting to access them. For this to work, you also need to be using the [latest pre-release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/download/v2023.8.23.0-rc.1/HDoujin.Downloader-2023.8.23.0-rc.1-win.zip).

Let me know if there are any problems!

**Comment by mrstan3772** [comment]
This tends to reset all bookmarked chapters for publications that are redirected to another URL. Otherwise, create a duplicate bookmark with the new URL.

Redirect URLs Examples:
https://asuracomics.com/manga/2091190535-academys-undercover-professor => https://asuracomics.com/manga/4243005272-academys-undercover-professor
https://asuracomics.com/manga/2091190535-life-of-a-magic-academy-mage => https://asuracomics.com/manga/4243005272-life-of-a-magic-academy-mage

404 Error Example:
https://asuracomics.com/manga/2091190535-return-of-the-disaster-class-hero

**Comment by HDoujinDownloader** [comment]
> This tends to reset all bookmarked chapters for publications that are redirected to another URL

I wonder if the chapter URLs change too? I notice they use a different numeric prefix from the manga they belong to, but I haven't checked if they actively change. If that's the case, they would be detected as new chapters.

**Comment by mrstan3772** [comment]
> > This tends to reset all bookmarked chapters for publications that are redirected to another URL
> 
> I wonder if the chapter URLs change too? I notice they use a different numeric prefix from the manga they belong to, but I haven't checked if they actively change. If that's the case, they would be detected as new chapters.

Yes for https://asuracomics.com/manga/4243005272-life-of-a-magic-academy-mage/ Chapter 58 and 57 are not same prefix. 

We need to find a way to ignore the prefix or accept unique regex pattern ?

**Comment by Zervox** [comment]
this is because their way of updating the prefix is lagging behind. I've often noticed that not all of the comics update the prefix at the same time, and it seems like you are saying here that this applies also to the manga chapters.  they will eventually end up all being the same. 

personally I am glad just it finds the chapter then adds it as a new duplicate unlike before where I had to manually update the prefix for every single one, because then I won't have to look at all the red warnings unless the url has changed completely.

I've noticed that flamescans and luminous also uses this prefix but they are not updated the way it is for Asura, makes me wonder if they are only doing this semi automatically.

**Comment by HDoujinDownloader** [comment]
I'm not sure of the best way of handling this right now, but I'll give it some thought.

Stripping the prefix before comparing chapter URLs is an option, or comparing titles instead of URLs when checking for new chapters.

There is a workaround in the meantime you can try if you want: If you click the settings button on the top right of the bookmarks panel (accessible by going to **_Manga > Bookmarks_**), and then under "Checking", enable the "fast bookmark checking" setting. This disables the URL comparisons and just looks at the number of chapters to decide which ones are new (e.g. if there were 100 chapters before and 102 now, the last two will be considered new). This works well when the site never removes chapters.
