### ISSUE TITLE
Add support for makimaaaaa.com

### ISSUE THREAD

**Issue by noneplayers** [HDoujinDownloader/HDoujinDownloader#275]
Could you please add support for makimaaaaa.com

**Comment by HDoujinDownloader** [comment]
Added! It should be working the next time you restart HDoujin Downloader.

**Comment by noneplayers** [comment]
it does not work, can you check?
https://makimaaaaa.com/manga/kichiku-eiyuu/
![Screenshot_742](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/65090809/b4c1eb3c-1c0b-4a4f-b596-c7a2108d146a)

**Comment by HDoujinDownloader** [comment]
This is what you would see if the module for this site wasn't loading for some reason. Either it failed to update, or the `lib` folder is missing in your HDoujin Downloader folder. Make sure you've downloaded and extracted the [full ZIP archive](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/download/v2023.11.8.0/HDoujin.Downloader-2023.11.8.0-win.zip) version of HDoujin Downloader instead of using the standalone executable.

If the issue persists, open the log by going to _**Tools > Log Viewer**_ and then try adding a URL from the site to the download queue. Tell me what it says, and I'll see what I can advise.

**Comment by noneplayers** [comment]
it works, Thank you

![image](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/65090809/855e4fad-ecce-4634-95c7-8070e059ec6b)
