### ISSUE TITLE
Windows Defender Detects Trojan in the New Update

### ISSUE THREAD

**Issue by dew152** [HDoujinDownloader/HDoujinDownloader#281]
I updated to the new version and Windows Defender immediately detected two Trojans in the updated files. The Trojan is classified as bearfoos. Why would the dev do such a thing after so many years?

Anyways be careful everyone!

**Comment by HDoujinDownloader** [comment]
It’s just a false-positive– This happens a lot when I release an update, because the new executable is unrecognized. I often have to resubmit it for whitelisting every time. I try to do that before uploading it, but sometimes it still happens.

It doesn’t seem to be complaining with the latest definitions update ([VirusTotal](https://www.virustotal.com/gui/file/1ee31c5b1fe8535d2cf51e71c3e448be35bfcc0c0b4fa286d4b342c77090fa5a)). Try running Windows Update to update Windows Defender's definitions and see if it still happens.

There is one issue I'm aware of where having automatic backups enabled will trigger Windows Defender (why, I have no idea). I ended up having to disable automatic backups by default because of this. If you had them enabled, it would've created a backup prior to the update, which may have triggered it.
