### ISSUE TITLE
Why does HDoujin detect the website but its chapters appear as: N/A

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#320]
![Screenshot 2024-04-30 22-24-34](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/36248950/b78dc207-c151-49e3-9d2c-c610ac4bc596)
The thing here is that when I try to download content from some sites the page appears but not the chapters

**Comment by HDoujinDownloader** [comment]
What website is this? Could you send me an example URL to look at?

**Comment by Infel1** [comment]
Yes! https://taurusmanga.com/manga/aumento_de_nivel_10_000_anos_en_el_futuro/

**Comment by HDoujinDownloader** [comment]
I was going to say, it should be working as expected now that I explicitly added support for it.

The fact it wasn't seeing the chapters before was because it was trying its best to make sense of the URL you gave it without actually knowing which module it should be assigned to. Now that I've explicitly assigned it a module, it knows how to properly extract the chapters.
