### ISSUE TITLE
exh***ai "page collection error"

### ISSUE THREAD

**Issue by mrAnonymus69** [HDoujinDownloader/HDoujinDownloader#360]
when trying to download it gives 
![image](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/172566215/04ce2c03-4a52-4713-9e5e-e89255257de2)

this is one of the url
- https://exhentai.org/g/2907756/f20849b44e/

**Comment by HDoujinDownloader** [comment]
Just to be certain: Did you add a login under _**Settings > Logins**_? I assume you did since you were able to add the galleries to the download queue in the first place, but just making sure.

I can't seem to reproduce the problem on my end. If you go to **_Tools > Log Viewer_** and then try to download a gallery, do you see any errors appear there?

**Comment by mrAnonymus69** [comment]
> Just to be certain: Did you add a login under _**Settings > Logins**_? I assume you did since you were able to add the galleries to the download queue in the first place, but just making sure.
> 
> I can't seem to reproduce the problem on my end. If you go to **_Tools > Log Viewer_** and then try to download a gallery, do you see any errors appear there?

You're right, logins resolve the problems, my two brain cells are missing this. 
Many thanks
