### ISSUE TITLE
Add uncensored archive sites

### ISSUE THREAD

**Issue by mrreal100** [HDoujinDownloader/HDoujinDownloader#374]
Adding the list of sites to add:

- [x] https://spy.fakku.cc
- [x] https://fakku.cc
- [x] https://koharu.to/
- [x] https://hentainexus.com/
- [x] https://18kami.com/

**Comment by HDoujinDownloader** [comment]
The last 3 are already supported, but I noticed it wasn't picking up the chapter list for galleries that have it on 18Kami. This has now been fixed, so all 3 of them should be working as expected.

As for the first 2, it appears the website is down right now. I'll have to check on it later to see if it's working again.

**Comment by Drewsky56** [comment]
It looks like both https://spy.fakku.cc/ and https://fakku.cc/ redirect to https://hentalk.pw/

**Comment by HDoujinDownloader** [comment]
It should be working now. 

If have any problems adding galleries to the download queue though, go to **_Tools > General settings > Advanced settings_** from the menu at the top of the program window, and disable the `Network.Http.BrotiDecompressionEnabled` setting. There are some quirks with this site that prevent galleries from being added to the queue when that setting is enabled (I'll have this fixed with the next program update).
