### ISSUE TITLE
USE FMD2 Instead !!!

### ISSUE THREAD

**Issue by ElryGH** [HDoujinDownloader/HDoujinDownloader#404]
Everything in this Tool is also in [Free Manga Downloader 2](https://github.com/dazedcat19/FMD2) for completly FREE !!
Just a warning, this tool has a Download limit and wants you to pay !

**Comment by HDoujinDownloader** [comment]
The download limit is no secret, this information is openly available on the product homepage.

While this repository is fairly new, I've been maintaining HDoujin Downloader for over 10 years, starting back when DomDomSoft was the only usable alternative. Similar projects have come and gone during this time, including FMD, which had a brief death before being resurrected as FMD2.

HDoujin Downloader has always been my passion project, originally created just for my own use. Over time, other people discovered it and found it useful for their own needs as well. Which honestly means the world to me-- It's a great feeling knowing that other people are using something that you created. It's why I've always taken user feedback very seriously. I want to make something that's as useful as it can be for everyone.

There used to be no download limit. I think I added it sometime in 2016. It was something I did as the project grew more popular and maintaining it started to consume my life. And I don't mean this in a bad way-- I enjoy working on this, it makes me happy, but it does take up a ridiculous amount of my time.

Trust me when I say I dislike paywalls as much as the next guy. I've given out tons of keys over the years to people that hit me up because they genuinely couldn't afford it, because I'm not trying to restrict it in that way. It's about getting some kind of realistic return on my time, as miniscule as it may be (I'd be better off financially if I put the same number of hours into a job at McDonald's). You could argue that the time investment would be less if it was open source, but let's be honest: These projects are generally only actively maintained by one or two dedicated developers.

That said, I intend to make the entire application open source some day, and publishing the modules like this was the first step in that direction. I don't want this project to die with me, so one day I'll have to pass the torch. I'm currently in the process of pulling out large chunks of the client into libraries so they can be used in other applications, so look forward to that.

As for whether you should use HDoujin Downloader or an alternative like FMD, that's up to you and your needs. Some people like that FMD has search functionality; some people like that HDD has more conversion options and metadata features. You are welcome to discuss other projects in good faith.

Peace! ✌️✌️

**Comment by ElryGH** [comment]
Im amazed at this response, im seriously sorry for my negativity towards you or your project.
I really thought this is some attempt at a scam and not some passion project that was a thing before FMD2.

And im really sorry for what i did to your comment section on your website, i was 100% convinced that it was to make a quick buck from people that dont know better.

I hope you can accept my apology.

**Comment by ElryGH** [comment]
@HDoujinDownloader btw is there any chance for a linux build ?

**Comment by HDoujinDownloader** [comment]
No worries man, we're good. 👍

I know some people have had success running it on Linux [using Wine](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Using-HDoujin-Downloader-on-Linux-and-MacOS), but sometimes it's a bit iffy and certainly less than ideal.

The UI was created in WinForms, so unfortunately I will need to redo the whole thing at some point for true cross-platform support. I'll probably ultimately end up doing that using Avalonia.

There's a lot of spaghetti to untangle and UI decoupling to do (I had no idea what I was doing when I initially started this project), but I'm in the process of reorganizing the code base so it can at least be built as a cross-platform console app, and then people can create their own native front ends if they want. I've almost got that done, and then we'll go from there. 🙏

**Comment by manga-download-owner** [comment]
> Everything in this Tool is also in [Free Manga Downloader 2](https://github.com/dazedcat19/FMD2) for completly FREE !! Just a warning, this tool has a Download limit and wants you to pay !

You may check [List of Manga Downloaders](https://github.com/manga-download/hakuneko/issues/2602)
Based on the download numbers FMD2 seems quite niche these days...
