### ISSUE TITLE
File Size Not Loading after Update.

### ISSUE THREAD

**Issue by AzraeltheForgottenKing** [HDoujinDownloader/HDoujinDownloader#415]
Just Updated to the newest version of HDoujin Downloader, now whenever I add new URL's, or renew existing ones, the File Size is blank until the download has started. The issue with this is that it is also blank if the name/location is being used and there are already files, so I have to individually check every download to ensure its file size/location is actually empty/zero. So that I do not wind up accidentally duplicating downloads/items.

**Comment by HDoujinDownloader** [comment]
Has it been a minute since you last updated the program? A while back I changed the file size column behavior so that it's only calculated when the contents of the directory are changed (by HDoujin). This was because it was very slow to calculate for folders that had a lot of files, and it would bog down the UI sometimes.

You can revert back to the previous behavior by going to _**Tools > General settings**_ from the menu at the top of the program window, then "Advanced settings", then unchecking the `Interface.DownloadQueue.RefreshFileSizeLazily` setting.

You're not the first person to mention using it this way, though. I'll add a new "Downloaded" column in the next program update that will show a checkmark if there are any existing files for a given queue item. You'll be able to enable it by right-clicking anything in the download queue and selecting "Choose columns".

Hope this helps!
