### ISSUE TITLE
problem with cloudfare protect

### ISSUE THREAD

**Issue by Beji-kun** [HDoujinDownloader/HDoujinDownloader#5]
Hi,
I try  download from source https://mangafort.com/ and https://mangazone.cc/manga/ 
I guide from https://doujindownloader.com/blocked-by-cloudflares-ddos-protection-page/ but I cant douwnload :( 
Can you help me how do it?
Thank you

**Comment by HDoujinDownloader** [comment]
Neither of those sites were supported at the time this issue was submitted, so it wouldn't have worked even with a successful Cloudflare bypass. I went to add support for them, but it looks like neither of the sites are online anymore!

If you ever encounter issues with Cloudflare again, check out the guide [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Cloudflare) (the one you linked is outdated).
