### ISSUE TITLE
Fix missing chapters for lezhinus.com

### ISSUE THREAD

**Issue by Fallen98** [HDoujinDownloader/HDoujinDownloader#56]
I have send an email about this, but not sure if it was seen.

It seems when a chapter has a name in place of a number for example "Epilogue", it doesn't seem to download.

The error I got from the log:

`
02:04:25 http        [x] Exception was thrown when accessing https://www.lezhinus.com/lz-api/v2/cloudfront/signed-url/generate?contentId=&episodeId=&purchased=false&q=30&firstCheckType=P: System.Net.WebException: The remote server returned an error: (400) Bad Request.`

Also from time to time the Lezhin module seems to not work for example when checking for updates or adding a new link. But then after some time it starts working again.

**Comment by HDoujinDownloader** [comment]
I was able to reproduce the problem, and this should now be resolved the next time you start HDoujin Downloader.

> time to time the Lezhin module seems to not work for example when checking for updates or adding a new link

I'm not totally sure about this one, but it sounds like a rate-limiting situation. You can try adding rate limits to HDoujin Downloader by going to **_Tools > Preferences > Timing & Delays_** if the issue comes up a lot, and it should hopefully help.
